// AUTO-GENERATED by web_dev/build/build_headers.py — DO NOT EDIT MANUALLY
// Source: web_dev\src\app.js
static const char *app_js PROGMEM = R"DTUGW(document.addEventListener('alpine:init',()=>{
 Alpine.store('app',{
 
 data:{},
 info:{},
 dtuData:{warningCount:0,warningsActive:0,warningsLastUpdate:0,warnings:[]},
 events:{events:[],statistics:{eventCount:0}},
 
 setupMode:false,
 wifiNetworks:[],
 setupSelectedSSID:'',
 setupPassword:'',
 setupLoading:false,
 drawerOpen:false,
 drawerTab:'wifi',
 showWarnings:false,
 showPowerLimit:false,
 showEvents:false,
 showRebootOverlay:false,
 rebootStatus:'Applying settings...',
 willReboot:false,
 rebootTarget:null,
 fwFile:null,
 updateProgress:-1,
 _updateTimeout:0,
 _updateInterval:null,
 _updateStatus:'',
 toasts:[],
 _toastSeq:0,
 _firstSetupDone:false,
 passVis:{wifiPass:false,mqttPass:false},
 passActual:{wifiPass:'',mqttPass:''},
 
 isLoading:true,
 _dataReceived:false,
 _infoReceived:false,
 
 backendReachable:true,
 _lastSuccessfulFetch:null,
 _connectionLossTimeout:null,
 _connectionCheckInterval:null,
 
 _wifiScanInitiated:false,
 
 reloadBarPct:100,
 _lastResponseTime:0,
 _dtuDataCycleMs:31000,
 
 ui:{gridFlash:false,pv0Flash:false,pv1Flash:false},
 
 form:{
 wifiSSID:'',wifiPass:'',
 dtuIp:'',dtuCycle:31,
 dtuCloudPause:true,remoteDisplay:false,remoteSummary:false,
 batteryMonitor:false,
 ohActive:false,ohIp:'',ohPrefix:'',
 mqttActive:false,mqttTLS:false,
 mqttIpPort:'',mqttUser:'',mqttPass:'',mqttTopic:'',mqttHA:false,mqttOpenDTU:false,
 powerLimit:100,
},
 
 init(){
 this._fetchData();
 this._fetchInfo();
 this._fetchDtuData();
 this._fetchEvents();
 setInterval(()=>this._fetchData(),1000);
 setInterval(()=>this._fetchInfo(),5000);
 setInterval(()=>this._fetchDtuData(),7500);
 setInterval(()=>this._fetchEvents(),15000);
 setInterval(()=>this._checkVersion(),300000);
 
 setInterval(()=>{
 if(this._lastResponseTime===0){
 
 this.reloadBarPct=100;
}else{
 const elapsed=Date.now()-this._lastResponseTime;
 const remaining=Math.max(0,this._dtuDataCycleMs-elapsed);
 this.reloadBarPct=(remaining/this._dtuDataCycleMs)*100;
}
},100);
},
 
 
 async _get(url,timeout=10000){
 const controller=new AbortController();
 const timeoutId=setTimeout(()=>controller.abort(),timeout);
 try{
 const res=await fetch(url,{cache:'no-store',signal:controller.signal});
 clearTimeout(timeoutId);
 if(!res.ok)throw new Error(`${url}→ ${res.status}`);
 return res.json();
}catch(err){
 clearTimeout(timeoutId);
 throw err;
}
},
 async _post(url,params){
 const body=new URLSearchParams(params);
 const res=await fetch(url,{
 method:'POST',
 headers:{'Content-Type':'application/x-www-form-urlencoded'},
 body:body.toString(),
});
 if(!res.ok)throw new Error(`${url}→ ${res.status}`);
 return res.json();
},
 
 async _fetchData(){
 try{
 const d=await this._get('/api/data.json');
 
 if(this.data.grid&&d.grid.p!==this.data.grid.p)this._flash('grid');
 if(this.data.pv0&&d.pv0.p!==this.data.pv0.p)this._flash('pv0');
 if(this.data.pv1&&d.pv1.p!==this.data.pv1.p)this._flash('pv1');
 
 if(this.data.lastResponse!==d.lastResponse){
 this._lastResponseTime=Date.now();
 
 this._dtuDataCycleMs=(this.info.dtuConnection?.dtuDataCycle??31)*1000;
}
 this.data=d;
 
 if(!this._dataReceived){
 this._dataReceived=true;
 this._updateLoadingState();
}
 
 const gridP=isNaN(d.grid?.p)?'--':d.grid.p.toFixed(0);
 document.title=`${gridP}W — dtuGateway`;
 
 if(!this.backendReachable){
 this.backendReachable=true;
 this._resetConnectionLossTimer();
 this.addToast('success','Connection restored');
}
 
 this._lastSuccessfulFetch=Date.now();
 this._resetConnectionLossTimer();
}catch(err){
 
 this._handleFetchError(err);
}
},
 async _fetchInfo(){
 try{
 this.info=await this._get('/api/info.json',5000);
 
 this._dtuDataCycleMs=(this.info.dtuConnection?.dtuDataCycle??31)*1000;
 
 
 if(!this._infoReceived){
 this._infoReceived=true;
 this._updateLoadingState();
}
 
 
 
 if(!this._firstSetupDone&&(this.info.initMode===1||this.info.wifiConnection?.wifiSsid==='')){
 this._firstSetupDone=true;
 this.setupMode=true;
 this._scanWifiNetworks();
}
}catch(_){}
},
 async _fetchDtuData(){
 try{
 const d=await this._get('/api/dtuData.json');
 
 if(d.warnings?.length){
 d.warnings.sort((a,b)=>b.timestampStart-a.timestampStart);
 d.warningsActive=d.warnings.filter(w=>w.timestampStop===0).length;
 d.warningCount=d.warnings.length;
}else{
 d.warningsActive=0;
 d.warningCount=0;
}
 this.dtuData=d;
}catch(_){}
},
 async _fetchEvents(){
 try{
 this.events=await this._get('/api/dtuEvents.json');
}catch(_){}
},
 async _checkVersion(){
 try{
 const d=await this._get('/updateGetInfo');
 if(this.info.firmware){
 this.info.firmware.versionServer=d.versionServer;
 this.info.firmware.updateAvailable=d.updateAvailable;
 this.info.firmware.selectedUpdateChannel=d.selectedUpdateChannel;
}
}catch(_){}
},
 
 _flash(channel){
 const key=`${channel}Flash`;
 this.ui[key]=false;
 
 requestAnimationFrame(()=>{
 this.ui[key]=true;
 setTimeout(()=>{this.ui[key]=false;},700);
});
},
 
 _updateLoadingState(){
 
 if(this._dataReceived&&this._infoReceived){
 this.isLoading=false;
}
},
 
 _resetConnectionLossTimer(){
 
 if(this._connectionLossTimeout){
 clearTimeout(this._connectionLossTimeout);
 this._connectionLossTimeout=null;
}
 
 this._connectionLossTimeout=setTimeout(()=>{
 if(!this.backendReachable)return;
 if(this._lastSuccessfulFetch&&Date.now()-this._lastSuccessfulFetch>10000){
 this.backendReachable=false;
 this.addToast('error','Connection to gateway lost');
}
},10000);
},
 _handleFetchError(err){
 
 
 if(this.backendReachable&&!this._connectionLossTimeout){
 this._connectionLossTimeout=setTimeout(()=>{
 if(this.backendReachable){
 this.backendReachable=false;
 this.addToast('error','Connection to gateway lost');
}
},10000);
}
},
 
 
 fmt(val,decimals=1,unit=''){
 if(val===undefined||val===null||isNaN(val)){
 return `--${unit?' '+unit:''}`;
}
 return `${Number(val).toFixed(decimals)}${unit?' '+unit:''}`;
},
 
 
 formatMillis(ms){
 if(!ms&&ms!==0)return '--';
 const totalSec=Math.floor(ms/1000);
 const s=totalSec%60;
 const m=Math.floor(totalSec/60)%60;
 const h=Math.floor(totalSec/3600)%24;
 const d=Math.floor(totalSec/86400);
 const pad=v=>String(v).padStart(2,'0');
 return d>0
?`${d}d ${pad(h)}:${pad(m)}:${pad(s)}`
:`${pad(h)}:${pad(m)}:${pad(s)}`;
},
 formatTs(ts,mode='time'){
 if(!ts)return '--:--:--';
 const d=new Date(ts*1000);
 if(mode==='time'){
 return d.toLocaleTimeString('de-DE');
}
 if(mode==='date'){
 return d.toLocaleDateString('de-DE');
}
 if(mode==='short'){
 const dd=String(d.getDate()).padStart(2,'0');
 const mm=String(d.getMonth()+1).padStart(2,'0');
 const hh=String(d.getHours()).padStart(2,'0');
 const min=String(d.getMinutes()).padStart(2,'0');
 return `${dd}.${mm}. ${hh}:${min}`;
}
 if(mode==='datetime'){
 return d.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'})
+' '+d.toLocaleTimeString('de-DE');
}
 return String(ts);
},
 
 warnDetail(w){
 if(!w.data0)return null;
 const msg=w.message.toLowerCase().replace(/-/g,'');
 let l0='data0',v0=String(w.data0);
 let l1='data1',v1=String(w.data1);
 if(msg.includes('undervoltage')||msg.includes('overvoltage')){
 l0='measured voltage';v0=(w.data0/10).toFixed(2)+' V';
 l1=msg.includes('undervoltage')?'minimal voltage':'maximum voltage';
 v1=(w.data1/10).toFixed(2)+' V';
}else if(msg.includes('overfrequency')||msg.includes('underfrequency')){
 l0='measured frequency';v0=(w.data0/100).toFixed(2)+' Hz';
 l1=msg.includes('underfrequency')?'minimum frequency':'maximum frequency';
 v1=(w.data1/100).toFixed(2)+' Hz';
}else if(msg.includes('over temperature')){
 l0='measured temperature';v0=(w.data0/100).toFixed(2)+' °C';
 l1='maximum temperature';v1=(w.data1/100).toFixed(2)+' °C';
}
 return{l0,v0,l1,v1};
},
 
 connStateLabel(){
 const labels=[
 'offline','connected','cloud pause','reconnecting',
 'rebooting','connect error','stopped','reboot inverter',
];
 return labels[this.data.dtuConnState]??'unknown';
},
 connBadgeClass(){
 const s=this.data.dtuConnState;
 if(s===1)return 'ok';
 if(s===2)return 'paused';
 if(s===3||s===4||s===7)return 'warn';
 return 'error';
},
 dtuErrorLabel(){
 const labels=['ok','no time','time error','data error','last TX done'];
 return labels[this.data.dtuErrorState]??'no info';
},
 
 
 
 isSolarMonitor(){
 const c=this.info.dtuConnection;
 return!!(c?.dtuRemoteDisplay_SolarMonitor||c?.dtuRemoteSummaryDisplay);
},
 isBatteryMonitor(){
 return!!(this.info.dtuConnection?.dtuRemoteDisplay_BatteryMonitor);
},
 isMonitorMode(){
 return this.isSolarMonitor()||this.isBatteryMonitor();
},
 monitorLabel(){
 const s=this.isSolarMonitor(),b=this.isBatteryMonitor();
 if(s&&b)return 'solar&battery monitor';
 if(s)return 'solar monitor';
 return 'battery monitor';
},
 monitorGlow(){
 const s=this.isSolarMonitor(),b=this.isBatteryMonitor();
 if(s&&b)return 'monitor-glow--both';
 if(s)return 'monitor-glow--solar';
 return 'monitor-glow--battery';
},
 pageTitle(){
 const dev=this.info.dtuConnection?.deviceData;
 let model=dev?.inverter_model??'HMS-xxxW-xT';
 if(model==='--')model='HMS-xxxW-xT';
 if(this.info.dtuConnection?.dtuRemoteDisplay)return `Hoymiles ${model}— Remote Display`;
 const s=this.isSolarMonitor(),b=this.isBatteryMonitor();
 if(s&&b)return `Hoymiles ${model}— Solar&Battery Monitor`;
 if(s)return `Hoymiles ${model}— Solar Monitor`;
 if(b)return `Hoymiles ${model}— Battery Monitor`;
 return `Hoymiles ${model}— Gateway`;
},
 
 openDrawer(tab='wifi'){
 this.drawerTab=tab;
 this.drawerOpen=true;
 this._populateForm();
 
 if(tab==='wifi'){
 if(this.info.wifiConnection?.foundNetworks?.length){
 this._silentWifiScan();
}else{
 this.requestWifiScan();
}
}
},
 closeDrawer(){
 this.drawerOpen=false;
 this.rebootTarget=null;
},
 _populateForm(){
 const i=this.info;
 if(!i||!i.wifiConnection)return;
 const wc=i.wifiConnection;
 const dtu=i.dtuConnection??{};
 const oh=i.openHabConnection??{};
 const mqtt=i.mqttConnection??{};
 this.form.wifiSSID=wc.wifiSsid??'';
 
 if(wc.wifiPassword){
 this.passActual.wifiPass=wc.wifiPassword;
 this.form.wifiPass='••••••••';
}else{
 this.passActual.wifiPass='';
 this.form.wifiPass='';
}
 this.form.dtuIp=dtu.dtuHostIpDomain??'';
 this.form.dtuCycle=dtu.dtuDataCycle??31;
 this.form.dtuCloudPause=!!dtu.dtuCloudPause;
 this.form.remoteDisplay=!!dtu.dtuRemoteDisplay;
 
 this.form.remoteSummary=!!(dtu.dtuRemoteSummaryDisplay||dtu.dtuRemoteDisplay_SolarMonitor);
 this.form.batteryMonitor=!!dtu.dtuRemoteDisplay_BatteryMonitor;
 this.form.ohActive=!!oh.ohActive;
 this.form.ohIp=oh.ohHostIp??'';
 this.form.ohPrefix=oh.ohItemPrefix??'';
 this.form.mqttActive=!!mqtt.mqttActive;
 this.form.mqttTLS=!!mqtt.mqttUseTLS;
 this.form.mqttIpPort=mqtt.mqttIp?`${mqtt.mqttIp}:${mqtt.mqttPort}`:'';
 this.form.mqttUser=mqtt.mqttUser??'';
 
 if(mqtt.mqttPass){
 this.passActual.mqttPass=mqtt.mqttPass;
 this.form.mqttPass='••••••••';
}else{
 this.passActual.mqttPass='';
 this.form.mqttPass='';
}
 this.form.mqttTopic=mqtt.mqttMainTopic??'';
 this.form.mqttHA=!!mqtt.mqttHAautoDiscoveryON;
 this.form.mqttOpenDTU=!!mqtt.mqttOpenDTUtopics;
 this.form.powerLimit=this.data.inverter?.pLimSet??100;
},
 
 async saveWifi(){
 if(this.info.protectSettings)return;
 try{
 await this._post('/updateWifiSettings',{
 wifiSSIDsend:this.form.wifiSSID,
 wifiPASSsend:this.form.wifiPass!=='••••••••'?this.form.wifiPass:this.passActual.wifiPass,
});
 
 
 this.willReboot=this.info.initMode===1;
 this.drawerOpen=false;
 
 if(this.willReboot){
 this.showRebootOverlay=true;
 this.rebootStatus='Device is rebooting...';
 this._waitForDeviceReconnect();
}else{
 this._toast('WiFi settings saved','success');
}
}catch(e){
 this._toast('Save failed:'+e.message,'error');
}
},
 async saveDtu(){
 if(this.info.protectSettings)return;
 try{
 
 const currentRemoteDisplay=!!this.info.dtuConnection?.dtuRemoteDisplay;
 const currentSolarMonitor=!!this.info.dtuConnection?.dtuRemoteDisplay_SolarMonitor;
 const currentBatteryMonitor=!!this.info.dtuConnection?.dtuRemoteDisplay_BatteryMonitor;
 
 const newRemoteDisplay=(this.form.remoteDisplay&&!this.form.remoteSummary&&!this.form.batteryMonitor);
 const newSolarMonitor=(!this.form.remoteDisplay&&this.form.remoteSummary);
 const newBatteryMonitor=(!this.form.remoteDisplay&&this.form.batteryMonitor);
 
 
 this.willReboot=(currentRemoteDisplay!==newRemoteDisplay)||
(currentSolarMonitor!==newSolarMonitor)||
(currentBatteryMonitor!==newBatteryMonitor);
 
 await this._post('/updateDtuSettings',{
 dtuHostIpDomainSend:this.form.dtuIp,
 dtuDataCycleSend:this.form.dtuCycle,
 dtuCloudPauseSend:this.form.dtuCloudPause?'1':'0',
 remoteDisplayActiveSend:newRemoteDisplay?'1':'0',
 remoteSummaryDisplayActiveSend:newSolarMonitor?'1':'0',
 remoteBatteryDisplayActiveSend:newBatteryMonitor?'1':'0',
});
 
 this.drawerOpen=false;
 
 if(this.willReboot){
 this.showRebootOverlay=true;
 this.rebootStatus='Device is rebooting...';
 this._waitForDeviceReconnect();
}else{
 this._toast('DTU settings saved','success');
 this._fetchInfo();
}
}catch(e){
 this._toast('Save failed:'+e.message,'error');
}
},
 isSettingsProtected(){
 return!!this.info.protectSettings;
},
 async saveBindings(){
 if(this.info.protectSettings)return;
 try{
 await this._post('/updateBindingsSettings',{
 openhabActiveSend:this.form.ohActive?'1':'0',
 openhabIPSend:this.form.ohIp,
 ohItemPrefixSend:this.form.ohPrefix,
 mqttActiveSend:this.form.mqttActive?'1':'0',
 mqttUseTLSSend:this.form.mqttTLS?'1':'0',
 mqttIPSend:this.form.mqttIpPort,
 mqttUserSend:this.form.mqttUser,
 mqttPasswordSend:this.form.mqttPass!=='••••••••'?this.form.mqttPass:this.passActual.mqttPass,
 mqttMainTopicSend:this.form.mqttTopic,
 mqttHAautoDiscoveryONSend:this.form.mqttHA?'1':'0',
 mqttOpenDTUtopicsSend:this.form.mqttOpenDTU?'1':'0',
});
 
 
 this.willReboot=this.form.mqttActive;
 
 
 this.drawerOpen=false;
 this.showRebootOverlay=true;
 if(this.willReboot){
 this.rebootStatus='Device is rebooting...';
}else{
 this.rebootStatus='Applying settings...';
}
 
 this._waitForDeviceReconnect();
 
}catch(e){
 this._toast('Save failed:'+e.message,'error');
}
},
 async _waitForDeviceReconnect(){
 let attempts=0;
 const maxAttempts=150;
 const minDisplayTime=2000;
 const initialDelayTime=4000;
 const startTime=Date.now();
 
 const checkDevice=async()=>{
 attempts++;
 const elapsed=Math.ceil((Date.now()-startTime)/1000);
 this.rebootStatus=`${this.willReboot?'Rebooting':'Applying'}...(${elapsed}s)`;
 
 try{
 
 const res=await fetch('/api/info.json',{cache:'no-store'});
 if(res.ok){
 
 
 const displayedFor=Date.now()-startTime;
 if(displayedFor<minDisplayTime){
 setTimeout(()=>{
 this.showRebootOverlay=false;
 this._toast('Settings applied successfully!','success');
 this._fetchInfo();
},minDisplayTime-displayedFor);
 return;
}
 
 this.showRebootOverlay=false;
 this._toast('Settings applied successfully!','success');
 
 this._fetchInfo();
 return;
}
}catch(e){
 
}
 
 if(attempts<maxAttempts){
 setTimeout(checkDevice,500);
}else{
 
 this.showRebootOverlay=false;
 this._toast('Device offline for too long. Please check WiFi connection and refresh manually.','error');
}
};
 
 
 setTimeout(checkDevice,initialDelayTime);
},
 async savePowerLimit(){
 try{
 await this._post('/updatePowerLimit',{
 powerLimitSend:this.form.powerLimit,
});
 this._toast(`Power limit set to ${this.form.powerLimit}%`,'success');
 this.showPowerLimit=false;
}catch(e){
 this._toast('Save failed:'+e.message,'error');
}
},
 
 async setChannel(ch){
 try{
 await this._post('/updateOTASettings',{updateChannel:ch});
 if(this.info.firmware)this.info.firmware.selectedUpdateChannel=ch;
}catch(e){
 this._toast('Channel change failed','error');
}
},
 async startOnlineUpdate(){
 console.log('[UPDATE]Starting online update...');
 this.updateProgress=0;
 this._updateTimeout=60;
 this._updateStatus='preparing';
 try{
 console.log('[UPDATE]Posting to/doupdate');
 await this._post('/doupdate',{});
 console.log('[UPDATE]Post successful,starting progress poll');
 this._pollUpdateProgress();
}catch(e){
 console.error('[UPDATE]Update failed:',e);
 this._toast('Update failed:'+e.message,'error');
 this.updateProgress=-1;
 this._updateTimeout=0;
 this._updateStatus='';
}
},
 manualFwSelected(event){
 this.fwFile=event.target.files[0]??null;
 console.log('[UPDATE]File selected:',this.fwFile?.name);
},
 async uploadManualFirmware(){
 console.log('[UPDATE]Starting manual firmware upload...');
 if(!this.fwFile)return;
 const fd=new FormData();
 fd.append('update',this.fwFile);
 this.updateProgress=0;
 this._updateTimeout=60;
 this._updateStatus='preparing';
 
 
 console.log('[UPDATE]Starting progress poll immediately');
 this._pollUpdateProgress();
 
 
 try{
 console.log('[UPDATE]Uploading file:',this.fwFile.name);
 fetch('/doupdate',{method:'POST',body:fd})
 .then(res=>{
 console.log('[UPDATE]Upload response received:',res.status);
 if(!res.ok)throw new Error('Upload returned:'+res.statusText);
 console.log('[UPDATE]Upload completed successfully');
})
 .catch(e=>{
 console.error('[UPDATE]Upload error:',e);
 
});
}catch(e){
 console.error('[UPDATE]Upload failed to start:',e);
 this._toast('Upload failed:'+e.message,'error');
 this.updateProgress=-1;
 this._updateTimeout=0;
 this._updateStatus='';
 this.fwFile=null;
}
},
 _pollUpdateProgress(){
 console.log('[UPDATE]Starting poll for firmware update progress...');
 const MAX_TIMEOUT_SEC=60;
 let timeoutCounter=MAX_TIMEOUT_SEC;
 this._updateTimeout=MAX_TIMEOUT_SEC;
 
 
 const timeoutInterval=setInterval(()=>{
 timeoutCounter--;
 this._updateTimeout=timeoutCounter;
 console.log('[UPDATE]Timeout countdown:',timeoutCounter+'s');
 
 if(timeoutCounter<=0){
 console.log('[UPDATE]Timeout reached-clearing intervals');
 clearInterval(timeoutInterval);
 clearInterval(this._updateInterval);
 this._toast('⏱ Update timeout(60s)— restoring control…','warn');
 this.updateProgress=-1;
 this._updateTimeout=0;
 this._updateStatus='';
 this.fwFile=null;
}
},1000);
 
 
 this._updateInterval=setInterval(async()=>{
 try{
 const s=await this._get('/updateState');
 console.log('[UPDATE]API Response:',s);
 
 this.updateProgress=s.updateProgress??0;
 this._updateStatus=s.updateStateStr??'unknown';
 
 console.log('[UPDATE]Progress:',this.updateProgress+'%,Status:',this._updateStatus);
 
 
 if(s.updateState===6){
 console.log('[UPDATE]Error state detected!');
 clearInterval(timeoutInterval);
 clearInterval(this._updateInterval);
 this._toast('✗ Update failed — check serial logs for details','error');
 this.updateProgress=-1;
 this._updateTimeout=0;
 this._updateStatus='';
 this.fwFile=null;
 return;
}
 
 
 if(s.updateProgress>=100&&!s.updateRunning){
 console.log('[UPDATE]Update complete!');
 clearInterval(timeoutInterval);
 clearInterval(this._updateInterval);
 this._toast('✓ Update complete — reloading in 3 seconds…','success');
 
 
 setTimeout(()=>{
 this.updateProgress=-1;
 this._updateTimeout=0;
 this._updateStatus='';
 this.fwFile=null;
 location.reload();
},3000);
}
}catch(e){
 
 console.warn('[UPDATE]Poll error:',e);
}
},500);
},
 
 confirmReboot(target){
 this.rebootTarget=target;
},
 rebootLabel(){
 const labels={dtuGw:'dtuGateway',dtu:'DTU',mi:'Micro Inverter'};
 return labels[this.rebootTarget]??this.rebootTarget;
},
 async executeReboot(){
 const endpoints={dtuGw:'/rebootDtuGw',dtu:'/rebootDtu',mi:'/rebootMi'};
 const paramNames={dtuGw:'rebootDtuGw',dtu:'rebootDtu',mi:'rebootMi'};
 const url=endpoints[this.rebootTarget];
 if(!url)return;
 try{
 
 const params={};
 params[paramNames[this.rebootTarget]]='1';
 await this._post(url,params);
 this._toast(`${this.rebootLabel()}reboot initiated`,'warn');
 this.rebootTarget=null;
}catch(e){
 this._toast(`${this.rebootLabel()}reboot failed:${e.message}`,'error');
}
},
 
 
 async _silentWifiScan(){
 try{
 await this._get('/getWifiNetworks');
 
 
 let elapsed=0;
 const poller=setInterval(async()=>{
 elapsed+=250;
 await this._fetchInfo();
 if(!this.info.wifiConnection?.wifiScanIsRunning||elapsed>=15000){
 clearInterval(poller);
}
},250);
}catch(_){
 
}
},
 
 async requestWifiScan(){
 try{
 
 if(!this.info.wifiConnection){
 this.info.wifiConnection={foundNetworks:[],wifiScanIsRunning:0};
}
 this.info.wifiConnection.foundNetworks=[];
 this.info.wifiConnection.wifiScanIsRunning=1;
 this._wifiScanInitiated=true;
 await this._get('/getWifiNetworks');
 
 let elapsed=0;
 const poller=setInterval(async()=>{
 elapsed+=250;
 await this._fetchInfo();
 if(!this.info.wifiConnection?.wifiScanIsRunning||elapsed>=15000){
 clearInterval(poller);
 this._wifiScanInitiated=false;
}
},250);
}catch(_){
 this._wifiScanInitiated=false;
}
},
 
 _scanWifiNetworks(){
 
 this.setupLoading=true;
 this.requestWifiScan().then(()=>{
 this.setupLoading=false;
});
},
 async setupConnectWifi(){
 if(!this.setupSelectedSSID||!this.setupPassword){
 this._toast('Please select a network and enter password','error');
 return;
}
 this.setupLoading=true;
 try{
 await this._post('/updateWifiSettings',{
 wifiSSIDsend:this.setupSelectedSSID,
 wifiPASSsend:this.setupPassword,
});
 this._toast('WiFi settings saved. Reconnecting...','success');
 
 setTimeout(()=>{
 this.setupMode=false;
 this.setupSelectedSSID='';
 this.setupPassword='';
},3000);
}catch(e){
 this._toast('Failed to save WiFi:'+e.message,'error');
 this.setupLoading=false;
}
},
 
 async clearEvents(){
 try{
 await this._get('/api/dtuEventsClear');
 this.events={eventCount:0,events:[]};
 this._toast('Events cleared','success');
}catch(e){
 this._toast('Clear failed:'+e.message,'error');
}
},
 
 togglePassVis(field){
 this.passVis[field]=!this.passVis[field];
 
 if(this.passVis[field]){
 
 
 if(this.form[field]==='••••••••'){
 this.form[field]=this.passActual[field];
}
}else{
 
 if(this.passActual[field]){
 this.form[field]='••••••••';
}
}
},
 mqttSectionHint(){
 if(this.form.remoteDisplay){
 return 'Remote display active — subscribes to source dtuGateway MQTT topics.';
}
 if(this.form.remoteSummary){
 return 'Solar Monitor active — subscribes to PV power/daily yield topics.';
}
 return 'Publish all data to a MQTT broker and subscribe to power-limit commands.';
},
 
 
 _toast(msg,type=''){
 const id=++this._toastSeq;
 this.toasts.push({id,msg,type});
 setTimeout(()=>{
 this.toasts=this.toasts.filter(t=>t.id!==id);
},4000);
},
});
});
)DTUGW";
